name: dart_countries_states
description: >
  Just an example, not for publishing.
version: 0.0.6
author: Jose Fiorillo <jffiorillo@gmail.com>
homepage: https://github.com/jffiorillo/dart-countries-states

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  built_value:
    path: ../