name: dart_countries_states
description: A Dart project that contains all the countries information about them. Support multiple languages.
version: 0.0.8
homepage: https://github.com/jffiorillo/dart-countries-states

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^6.8.2
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.8.2
#  test: ^1.9.4
