name: dart_countries_states
description: A Dart project that contains all the countries and states
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
